export const productImages = {
  patato: "/images/patato.png",
  tomato: "/images/tomato.png",
  brownonion: "/images/brown-onion.png",
  redonion: "/images/red-onion.png",
  ladyfinger: "/images/lady-finger.png",
  greenchilli: "/images/greenchilli.png",
  spinch: "/images/spinch.png",
  lauki: "/images/lauki.png",
  greencucumber: "/images/greencucumber.png",
  cucumber: "/images/cucumber.png",
  bittergourd: "/images/bitter-gourd.png",
  carrot: "/images/carrot.png",
  pumkin: "/images/pumkin.png",
  cauliflower: "/images/cauliflower.png",
  cabbage: "/images/cabbage.png",
  brinjal: "/images/brinjal.png",
  fenugreekleaves: "/images/Fenugreek Leaves-मेथी.png",
  mustardgreens: "/images/mustardgreens.png",
  corianderleaves: "/images/corianderleaves.png",
  mint: "/images/mint.png",
  bathua: "/images/bathua.png",
  radish: "/images/radish.png",
  beetroot: "/images/beetroot.png",
  sweetpotato: "/images/sweetpatato.png",
  garlic: "/images/garlic.png",
  pointgourd: "/images/pointgourd-परवल.png",
  tinda: "/images/tinda.png",
  ginger: "/images/ginger.png",
  broccli: "/images/broccli.png",
  capsicum: "/images/capsicum.png",
  corn: "/images/corn.png",
  jackfruit: "/images/jackfruit.png",
  masroom: "/images/masroom.png",
  peas: "/images/peas.png",
  beans: "/images/beans.jpeg",
  chotebaingan: "/images/chotebaingan.jpeg",
  redcarrot: "/images/gajar.jpeg",
  kachri: "/images/kachri.jpeg",
  lemon: "/images/lemon.jpeg",
  motimirch: "/images/motimirch.jpeg",
  oldginger: "/images/oldginger.jpeg",
  starfruit: "/images/starfruit.jpeg",
  taroroot: "/images/taroroot.jpeg",
  tikhimirchi: "/images/tikhimirchi.jpeg",
  torai: "/images/torai.jpeg"
};

export const productLabels = {
  patato: "Potato (आलू)",
  tomato: "Tomato (टमाटर)",
  brownonion: "Brown Onion (सफेद प्याज़)",
  redonion: "Red Onion (लाल प्याज़)",
  ladyfinger: "Lady Finger (भिंडी)",
  greenchilli: "Green Chilli (हरी मिर्च)",
  spinch: "Spinach (पालक)",
  lauki: "Lauki (लौकी)",
  greencucumber: "Green Cucumber (हरा खीरा)",
  cucumber: "Cucumber (खीरा)",
  bittergourd: "Bitter Gourd (करेला)",
  carrot: "Carrot (गाजर)",
  pumkin: "Pumpkin (कद्दू)",
  cauliflower: "Cauliflower (फूलगोभी)",
  cabbage: "Cabbage (पत्तागोभी)",
  brinjal: "Brinjal (बैंगन)",
  fenugreekleaves: "Fenugreek Leaves (मेथी)",
  mustardgreens: "Mustard Greens (सरसों का साग)",
  corianderleaves: "Coriander Leaves (धनिया पत्ती)",
  mint: "Mint (पुदीना)",
  bathua: "Bathua (बथुआ)",
  radish: "Radish (मूली)",
  beetroot: "Beetroot (चुकंदर)",
  sweetpotato: "Sweet Potato (शकरकंद)",
  garlic: "Garlic (लहसुन)",
  pointgourd: "Pointed Gourd (परवल)",
  tinda: "Tinda (टिंडा)",
  ginger: "Ginger (अदरक)",
  broccli: "Broccoli (ब्रोकोली)",
  capsicum: "Capsicum (शिमला मिर्च)",
  corn: "Corn (मक्का)",
  jackfruit: "Jackfruit (कटहल)",
  masroom: "Mushroom (मशरूम)",
  peas: "Peas (मटर)",
  beans: "French Beans (बीन्स)",
  chotebaingan: "Small Brinjal (छोटे बैंगन)",
  redcarrot: "Red Carrot (देसी गाजर)",
  kachri: "Kachri (काचरी)",
  lemon: "Lemon (नींबू)",
  motimirch: "Moti Mirch (मोटी मिर्च)",
  oldginger: "Old Ginger (पुरानी अदरक)",
  starfruit: "Star Fruit (कमरख)",
  taroroot: "Taro Root (अरबी)",
  tikhimirchi: "Spicy Chilli (तीखी मिर्च)",
  torai: "Torai / Tori (तोरई)"
};

export const productCategories = {
  patato: "jad",
  tomato: "fruits",
  brownonion: "masale",
  redonion: "masale",
  ladyfinger: "hari-sabzi",
  greenchilli: "masale",
  spinch: "hari-sabzi",
  lauki: "hari-sabzi",
  greencucumber: "hari-sabzi",
  cucumber: "hari-sabzi",
  bittergourd: "hari-sabzi",
  carrot: "jad",
  pumkin: "hari-sabzi",
  cauliflower: "hari-sabzi",
  cabbage: "hari-sabzi",
  brinjal: "hari-sabzi",
  fenugreekleaves: "hari-sabzi",
  mustardgreens: "hari-sabzi",
  corianderleaves: "masale",
  mint: "masale",
  bathua: "hari-sabzi",
  radish: "jad",
  beetroot: "jad",
  sweetpotato: "jad",
  garlic: "masale",
  pointgourd: "hari-sabzi",
  tinda: "hari-sabzi",
  ginger: "masale",
  broccli: "hari-sabzi",
  capsicum: "hari-sabzi",
  corn: "fruits",
  jackfruit: "fruits",
  masroom: "mushroom",
  peas: "hari-sabzi",
  beans: "hari-sabzi",
  chotebaingan: "hari-sabzi",
  redcarrot: "jad",
  kachri: "fruits",
  lemon: "masale",
  motimirch: "masale",
  oldginger: "masale",
  starfruit: "fruits",
  taroroot: "jad",
  tikhimirchi: "masale",
  torai: "hari-sabzi"
};

export const productHinglish = {
  patato: "aloo aaloo aalu potato alu",
  tomato: "tamatar tomato",
  brownonion: "safed pyaz safed pyaaz white onion brown onion",
  redonion: "lal pyaz lal pyaaz onion pyaz",
  ladyfinger: "bhindi bindi lady finger okra",
  greenchilli: "hari mirch green chilli mirchi",
  spinch: "palak spinach",
  lauki: "lauki loki ghiya bottle gourd",
  greencucumber: "hara kheera green cucumber",
  cucumber: "kheera cucumber kakdi",
  bittergourd: "karela bitter gourd",
  carrot: "gajar carrot",
  pumkin: "kaddu pumpkin sitaphal",
  cauliflower: "phool gobhi phoolgobhi cauliflower",
  cabbage: "patta gobhi pattagobhi cabbage",
  brinjal: "baingan baigan brinjal eggplant",
  fenugreekleaves: "methi fenugreek leaves",
  mustardgreens: "sarson ka saag sarson saag mustard greens",
  corianderleaves: "dhaniya patti dhaniya coriander",
  mint: "pudina podina mint",
  bathua: "bathua bathua saag",
  radish: "mooli muli radish",
  beetroot: "chukandar beetroot chukander",
  sweetpotato: "shakarkand sweet potato",
  garlic: "lahsun lehsun garlic",
  pointgourd: "parwal point gourd",
  tinda: "tinda apple gourd",
  ginger: "adrak ginger",
  broccli: "broccoli brokli",
  capsicum: "shimla mirch capsicum bell pepper",
  corn: "makai bhutta sweet corn",
  jackfruit: "kathal jackfruit",
  masroom: "mushroom mashroom dhingri",
  peas: "matar peas green peas",
  beans: "beans french beans fali faliyaan",
  chotebaingan: "chote baingan baigan chota baingan",
  redcarrot: "desi gajar lal gajar gajar red carrot",
  kachri: "kachri kachari rajasthani kachri",
  lemon: "lemon nimbu neembu",
  motimirch: "moti mirch achari mirch bhavnagri mirchi",
  oldginger: "old ginger purani adrak sonth saunth",
  starfruit: "star fruit kamrakh starfruit",
  taroroot: "taro root arbi arvi ghuiya",
  tikhimirchi: "tikhi mirchi teekhi hari mirch spicy chilli",
  torai: "torai tori turiya ridge gourd"
};

export const default1KgPrices = {
  patato: 130, tomato: 110, brownonion: 100, redonion: 105,
  ladyfinger: 150, greenchilli: 90, spinch: 85, lauki: 80,
  greencucumber: 90, cucumber: 80, bittergourd: 40, carrot: 90,
  pumkin: 100, cauliflower: 130, cabbage: 80, brinjal: 110,
  fenugreekleaves: 80, mustardgreens: 80, corianderleaves: 65,
  mint: 65, bathua: 70, radish: 70, beetroot: 50, sweetpotato: 120,
  garlic: 80, pointgourd: 95, tinda: 105, ginger: 110,
  broccli: 150, capsicum: 130, corn: 110, jackfruit: 170, masroom: 180, peas: 110,
  beans: 70, chotebaingan: 80, redcarrot: 70, kachri: 100, lemon: 120,
  motimirch: 80, oldginger: 160, starfruit: 140, taroroot: 90, tikhimirchi: 100, torai: 70
};

export const productListOrder = [
  "patato", "tomato", "brownonion", "redonion", "ladyfinger",
  "greenchilli", "spinch", "lauki", "greencucumber", "cucumber",
  "bittergourd", "carrot", "pumkin", "cauliflower", "cabbage",
  "brinjal", "fenugreekleaves", "mustardgreens", "corianderleaves",
  "mint", "ginger", "bathua", "radish", "beetroot",
  "sweetpotato", "garlic", "pointgourd", "tinda", "broccli",
  "capsicum", "corn", "jackfruit", "masroom", "peas",
  "beans", "chotebaingan", "redcarrot", "kachri", "lemon",
  "motimirch", "oldginger", "starfruit", "taroroot", "tikhimirchi",
  "torai"
];
